version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "America/Argentina/Buenos_Aires"
    open-pull-requests-limit: 10
    reviewers:
      - "danizt"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"